Repository owlbarn/owl, pull requests merged in 2019-12, with the labels that each got.

#465 Owl-base linalg routines: LU decomposition
  src/base/linalg/owl_base_linalg_generic.ml
  test/unit_linalg_solver.ml
Labels: R&D, enhancement

#467 changes to algodiff tests + bug in algodiff concatenate
  src/base/algodiff/owl_algodiff_check.ml
  src/base/algodiff/owl_algodiff_check.mli
  src/base/algodiff/owl_algodiff_ops.ml
  test/unit_algodiff_matrix_generic.ml
  test/unit_linalg_solver.ml
Labels: enhancement

#470 Save and load Npy files
  owl.opam
  src/owl/dense/owl_dense_matrix_c.ml
  src/owl/dense/owl_dense_matrix_c.mli
  src/owl/dense/owl_dense_matrix_d.ml
  src/owl/dense/owl_dense_matrix_d.mli
  src/owl/dense/owl_dense_matrix_generic.ml
  src/owl/dense/owl_dense_matrix_generic.mli
  src/owl/dense/owl_dense_matrix_s.ml
  src/owl/dense/owl_dense_matrix_s.mli
  src/owl/dense/owl_dense_matrix_z.ml
  src/owl/dense/owl_dense_matrix_z.mli
  src/owl/dense/owl_dense_ndarray_c.ml
  src/owl/dense/owl_dense_ndarray_c.mli
  src/owl/dense/owl_dense_ndarray_d.ml
  src/owl/dense/owl_dense_ndarray_d.mli
  src/owl/dense/owl_dense_ndarray_generic.ml
  src/owl/dense/owl_dense_ndarray_generic.mli
  src/owl/dense/owl_dense_ndarray_s.ml
  src/owl/dense/owl_dense_ndarray_s.mli
  src/owl/dense/owl_dense_ndarray_z.ml
  src/owl/dense/owl_dense_ndarray_z.mli
  src/owl/dune
  src/owl/ext/owl_ext_dense_matrix.ml
  src/owl/ext/owl_ext_dense_ndarray.ml
  test/unit_dense_matrix.ml
  test/unit_dense_ndarray.ml
Labels: R&D, enhancement

#471 interface files to simplify .mli files in owl/dense
  src/owl/dense/owl_dense_matrix_c.mli
  src/owl/dense/owl_dense_matrix_d.mli
  src/owl/dense/owl_dense_matrix_intf.ml
  src/owl/dense/owl_dense_matrix_s.mli
  src/owl/dense/owl_dense_matrix_z.mli
  src/owl/dense/owl_dense_ndarray_c.ml
  src/owl/dense/owl_dense_ndarray_c.mli
  src/owl/dense/owl_dense_ndarray_d.mli
  src/owl/dense/owl_dense_ndarray_intf.ml
  src/owl/dense/owl_dense_ndarray_s.mli
  src/owl/dense/owl_dense_ndarray_z.ml
  src/owl/dense/owl_dense_ndarray_z.mli
  src/owl/linalg/owl_linalg_c.ml
  src/owl/linalg/owl_linalg_c.mli
  src/owl/linalg/owl_linalg_d.mli
  src/owl/linalg/owl_linalg_intf.ml
  src/owl/linalg/owl_linalg_s.mli
  src/owl/linalg/owl_linalg_z.ml
  src/owl/linalg/owl_linalg_z.mli
Labels: R&D, enhancement

#474 Port code to dune2
  .travis.yml
  dune-project
  owl-base.opam
  owl-plplot.opam
  owl-top.opam
  owl-zoo.opam
  owl.opam
  src/aeos/dune
  src/owl/dune
  test/dune
Labels: enhancement

#478 Temporary workaround to convolution bug
  src/owl/core/owl_ndarray_conv_impl.h
  src/owl/core/owl_ndarray_conv_stub.c
  test/unit_conv2d_generic.ml
Labels: bug

#476 use a separate module for algodiff instead of ndarray directly
  bin/owl_bin_viz.ml
  src/base/algodiff/owl_algodiff_ops.ml
  src/base/algodiff/owl_algodiff_ops_builder.ml
  src/base/algodiff/owl_algodiff_ops_builder_sig.ml
  src/base/algodiff/owl_base_algodiff_primal_ops.ml
  src/base/compute/owl_computation_cpu_eval.ml
  src/base/compute/owl_computation_operator.ml
  src/base/compute/owl_computation_operator_sig.ml
  src/base/core/owl_lazy.mli
  src/base/dense/owl_base_dense_ndarray.ml
  src/base/types/owl_types_ndarray_algodiff.ml
  src/base/types/owl_types_ndarray_basic.ml
  src/owl/algodiff/owl_algodiff.ml
  src/owl/algodiff/owl_algodiff_primal_ops.ml
  src/owl/dense/owl_dense_matrix.ml
  src/owl/dense/owl_dense_ndarray.ml
  src/owl/dune
  src/owl/neural/owl_neural.ml
  src/owl/optimise/owl_optimise.ml
  src/owl/optimise/owl_regression.ml
  test/unit_algodiff_diff.ml
  test/unit_algodiff_grad.ml
  test/unit_algodiff_matrix.ml
  test/unit_base_algodiff_diff.ml
  test/unit_base_algodiff_grad.ml
  test/unit_base_conv2d.ml
  test/unit_base_conv3d.ml
  test/unit_base_ndarray_core.ml
  test/unit_base_pool2d.ml
  test/unit_base_pool3d.ml
  test/unit_base_upsampling.ml
  test/unit_conv2d.ml
  test/unit_conv3d.ml
  test/unit_conv_mec_naive.ml
  test/unit_lazy.ml
  test/unit_linalg_solver.ml
  test/unit_ndarray_core.ml
  test/unit_pool2d.ml
  test/unit_pool3d.ml
  test/unit_upsampling.ml
Labels: R&D, enhancement

#479 Extend base linalg functions to complex numbers
  src/base/linalg/owl_base_linalg_generic.ml
  src/base/linalg/owl_base_linalg_generic.mli
  src/base/linalg/owl_base_linalg_intf.ml
  src/owl/linalg/owl_linalg_intf.ml
  test/unit_linalg_solver.ml
Labels: R&D, enhancement
